drive_to_charge_traffic_action_node:
  ros__parameters:
    waypoints: ["a", "b", "c","d","e","f"]
    a: [0.0, 0.0]
    b: [12.0, 0.0]
    c: [12.0, 8.0]
    d: [-10.0, 8.0]
    e: [-10.0, 5.0]
    f: [-2.0, -5.0]