locations:
  a: [0.0, 0.0, charging_station]
  b: [12.0, 0.0]
  c: [12.0, 8.0]
  d: [-10.0, 8.0]
  e: [-10.0, 5.0]
  f: [-2.0, -5.0, charging_station]

vehicle:
  taxi1: a

passenger:
  alice: c
  bob: d

connected:
  a: [b]
  b: [a, c, e]
  c: [b, d]
  d: [c, e]
  e: [b, d, f]
  f: [e]

traffic_heavy:
  b: [c]
  d: [e]